# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongorb}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["梁智敏(Gimi Liang)"]
  s.date = %q{2010-09-09}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{liang(dot)gimi(at)gmail(dot)com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "active_model_implementation.md",
     "lib/mongorb.rb",
     "lib/mongorb/conversion.rb",
     "lib/mongorb/dm-mongodb-adapter/adapter.rb",
     "lib/mongorb/dm-mongodb-adapter/comparison.rb",
     "lib/mongorb/dm-mongodb-adapter/comparison/core.rb",
     "lib/mongorb/dm-mongodb-adapter/comparison/extension.rb",
     "lib/mongorb/dm-mongodb-adapter/model.rb",
     "lib/mongorb/dm-mongodb-adapter/operation.rb",
     "lib/mongorb/dm-mongodb-adapter/property.rb",
     "lib/mongorb/dm-mongodb-adapter/repository.rb",
     "lib/mongorb/document.rb",
     "lib/mongorb/railtie.rb",
     "mongorb.gemspec",
     "test.rb",
     "test/fixtures.rb",
     "test/helper.rb",
     "test/models.rb",
     "test/test_active_model_compability.rb",
     "test/test_advance_query.rb",
     "test/test_crud.rb"
  ]
  s.homepage = %q{http://github.com/Gimi/mongorb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A mongodb Ruby object mapper based on ActiveModel and DataMapper.}
  s.test_files = [
    "test/test_active_model_compability.rb",
     "test/models.rb",
     "test/fixtures.rb",
     "test/test_advance_query.rb",
     "test/helper.rb",
     "test/test_crud.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["~> 3"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3"])
      s.add_runtime_dependency(%q<dm-core>, ["~> 1"])
      s.add_runtime_dependency(%q<mongo>, ["~> 1.0.8"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<forgery>, ["~> 0.3.4"])
    else
      s.add_dependency(%q<activemodel>, ["~> 3"])
      s.add_dependency(%q<activesupport>, ["~> 3"])
      s.add_dependency(%q<dm-core>, ["~> 1"])
      s.add_dependency(%q<mongo>, ["~> 1.0.8"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<forgery>, ["~> 0.3.4"])
    end
  else
    s.add_dependency(%q<activemodel>, ["~> 3"])
    s.add_dependency(%q<activesupport>, ["~> 3"])
    s.add_dependency(%q<dm-core>, ["~> 1"])
    s.add_dependency(%q<mongo>, ["~> 1.0.8"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<forgery>, ["~> 0.3.4"])
  end
end

